sudo: false

language: node_js
node_js:
  - "14.12.0"
cache:
  directories:
    - node_modules
install: npm install
env:
  - CI=ture
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
